from .utils_impl import UTILS_IMPLEMENTATIONS
from .text_impl import TEXT_IMPLEMENTATIONS

ALL_IMPLEMENTATIONS = {**UTILS_IMPLEMENTATIONS, **TEXT_IMPLEMENTATIONS}

__all__ = ['ALL_IMPLEMENTATIONS', 'UTILS_IMPLEMENTATIONS', 'TEXT_IMPLEMENTATIONS']
