import type { CatalogState } from '$types/stores/catalogs'

export const demoCatalogs = {
  providers: [
    {
      id: 'google',
      name: 'Google AI',
    },
    {
      id: 'openai',
      name: 'OpenAI',
    },
    {
      id: 'anthropic',
      name: 'Anthropic',
    },
    {
      id: 'local',
      name: 'Local (Ollama)',
    },
  ],
  models: [
    {
      id: 'gemini-1.5-flash',
      label: 'Gemini 1.5 Flash',
      vendor: 'Google',
      tag: 'Fast',
      badge: 'teal',
      providerId: 'google',
    },
    {
      id: 'gpt-4o',
      label: 'GPT-4o',
      vendor: 'OpenAI',
      tag: 'Balanced',
      badge: 'primary',
      providerId: 'openai',
    },
    {
      id: 'claude-3.7',
      label: 'Claude 3.7 Sonnet',
      vendor: 'Anthropic',
      tag: 'Deep',
      badge: 'violet',
      providerId: 'anthropic',
    },
    {
      id: 'llama-3.1-70b',
      label: 'Llama 3.1 70B',
      vendor: 'Local',
      tag: 'Private',
      badge: 'success',
      providerId: 'local',
    },
  ],
  voices: [
    {
      id: 'af_heart',
      name: 'Heart',
      lang: 'en-US',
      tags: ['warm', 'female'],
    },
    {
      id: 'af_bella',
      name: 'af_bella',
      lang: 'en',
      tags: ['bright'],
    },
    {
      id: 'af_sarah',
      name: 'af_sarah',
      lang: 'en',
      tags: ['clear'],
    },
    {
      id: 'af_nicole',
      name: 'af_nicole',
      lang: 'en',
      tags: ['soft'],
    },
    {
      id: 'af_sky',
      name: 'Sky',
      lang: 'en-US',
      tags: ['airy', 'female'],
    },
    {
      id: 'am_adam',
      name: 'Adam',
      lang: 'en-US',
      tags: ['deep', 'male'],
    },
    {
      id: 'am_michael',
      name: 'Michael',
      lang: 'en-US',
      tags: ['steady', 'male'],
    },
    {
      id: 'am_leo',
      name: 'am_leo',
      lang: 'en',
      tags: ['rich'],
    },
    {
      id: 'am_ryan',
      name: 'am_ryan',
      lang: 'en',
      tags: ['casual'],
    },
    {
      id: 'bf_emma',
      name: 'Emma',
      lang: 'en-GB',
      tags: ['female'],
    },
    {
      id: 'bm_george',
      name: 'George',
      lang: 'en-GB',
      tags: ['male'],
    },
    {
      id: 'jf_alpha',
      name: 'Alpha',
      lang: 'ja-JP',
      tags: ['female'],
    },
    {
      id: 'zm_yun',
      name: 'Yun',
      lang: 'zh-CN',
      tags: ['male'],
    },
    {
      id: 'ef_lucia',
      name: 'Lucia',
      lang: 'es-ES',
      tags: ['female'],
    },
  ],
  tools: [
    {
      name: 'shell',
      category: 'System',
      count: 4,
      enabled: true,
    },
    {
      name: 'filesystem',
      category: 'System',
      count: 6,
      enabled: true,
    },
    {
      name: 'github',
      category: 'Dev',
      count: 5,
      enabled: true,
    },
    {
      name: 'browser',
      category: 'Web',
      count: 3,
      enabled: true,
    },
    {
      name: 'gmail',
      category: 'Comms',
      count: 4,
      enabled: true,
    },
    {
      name: 'slack',
      category: 'Comms',
      count: 3,
      enabled: true,
    },
    {
      name: 'calendar',
      category: 'Comms',
      count: 3,
      enabled: true,
    },
  ],
  toolDefinitions: [
    {
      id: 'shell.run',
      name: 'shell.run',
      desc: 'Run a shell command and capture stdout / stderr.',
      category: 'shell',
      icon: 'terminal',
    },
    {
      id: 'file.read',
      name: 'file.read',
      desc: 'Read a file from the local sandbox.',
      category: 'file',
      icon: 'draft',
    },
    {
      id: 'file.write',
      name: 'file.write',
      desc: 'Create or overwrite a file with new content.',
      category: 'file',
      icon: 'edit_document',
    },
    {
      id: 'browser.fetch',
      name: 'browser.fetch',
      desc: 'Fetch a URL and return rendered HTML.',
      category: 'browser',
      icon: 'language',
    },
    {
      id: 'cron.schedule',
      name: 'cron.schedule',
      desc: 'Schedule a workflow with a cron expression.',
      category: 'cron',
      icon: 'schedule',
    },
    {
      id: 'text.summarise',
      name: 'text.summarise',
      desc: 'Compress a long passage to N sentences.',
      category: 'text',
      icon: 'format_align_left',
    },
  ],
  suggestions: [
    {
      id: 'suggestion-1',
      icon: 'code',
      tag: 'Code',
      title: 'Refactor my Python script',
      subtitle: 'Optimize performance and readability',
    },
    {
      id: 'suggestion-2',
      icon: 'edit_note',
      tag: 'Write',
      title: 'Draft a blog post outline',
      subtitle: 'On the future of on-device TTS',
    },
    {
      id: 'suggestion-3',
      icon: 'bug_report',
      tag: 'Debug',
      title: 'Find the bug in this hook',
      subtitle: 'State goes stale after fetch',
    },
    {
      id: 'suggestion-4',
      icon: 'account_tree',
      tag: 'Workflow',
      title: 'Build a daily digest flow',
      subtitle: 'Summarise + deliver to Slack at 9am',
    },
  ],
} satisfies CatalogState
