/* data.jsx — mock dataset for the KNIK redesign prototype */

const KNIK = {
  account: { name: "Amreet Kumar", handle: "amreet", initials: "AK" },

  recents: [
    {
      id: "c1",
      title: "Refactor Python pipeline",
      preview: "Replace inner loop with a generator…",
      at: "Today",
      pinned: true,
    },
    {
      id: "c2",
      title: "API docs for /v1/synth",
      preview: "Endpoint accepts voice + text…",
      at: "Today",
      pinned: false,
    },
    {
      id: "c3",
      title: "Debug React state",
      preview: "useEffect dependency missing…",
      at: "Yesterday",
      pinned: false,
    },
    {
      id: "c4",
      title: "Daily digest workflow",
      preview: "Trigger at 09:00 UTC, summarise…",
      at: "Mar 18",
      pinned: false,
    },
    {
      id: "c5",
      title: "MCP shell tool wrapper",
      preview: "Wrap tar + ssh into one call…",
      at: "Mar 12",
      pinned: false,
    },
  ],

  suggestions: [
    {
      icon: "code",
      tag: "Code",
      title: "Refactor my Python script",
      subtitle: "Optimize performance and readability",
    },
    {
      icon: "edit_note",
      tag: "Write",
      title: "Draft a blog post outline",
      subtitle: "On the future of on-device TTS",
    },
    {
      icon: "bug_report",
      tag: "Debug",
      title: "Find the bug in this hook",
      subtitle: "State goes stale after fetch",
    },
    {
      icon: "account_tree",
      tag: "Workflow",
      title: "Build a daily digest flow",
      subtitle: "Summarise + deliver to Slack at 9am",
    },
  ],

  models: [
    {
      id: "gemini-1.5-flash",
      label: "Gemini 1.5 Flash",
      vendor: "Google",
      tag: "Fast",
      badge: "teal",
    },
    {
      id: "gpt-4o",
      label: "GPT-4o",
      vendor: "OpenAI",
      tag: "Balanced",
      badge: "primary",
    },
    {
      id: "claude-3.7",
      label: "Claude 3.7 Sonnet",
      vendor: "Anthropic",
      tag: "Deep",
      badge: "violet",
    },
    {
      id: "llama-3.1-70b",
      label: "Llama 3.1 70B",
      vendor: "Local",
      tag: "Private",
      badge: "success",
    },
  ],

  thread: [
    {
      role: "user",
      content:
        "Refactor this Python script — it materialises the whole list and re-compiles the regex on every call.",
    },
    {
      role: "assistant",
      model: "gemini-1.5-flash",
      at: "12:41",
      thinking: [
        "Read hot path — `process()` builds a full list then filters",
        "Regex `PATTERN` recompiled inside the loop on each invocation",
        "`json.loads` is ~3× slower than `orjson` for this payload shape",
      ],
      tool: {
        name: "run_python",
        arg: "profile process() over 10k rows",
        result: "1.84s → 0.42s after changes",
      },
      content:
        "Three quick wins here:\n\n1. Replace the inner `for` loop with a generator so we never materialise the full list.\n2. Swap `json.loads` for `orjson` — about 3× faster on this payload.\n3. Hoist the regex out of the hot path so it isn't recompiled per call.",
      code: {
        lang: "python",
        body: 'PATTERN = re.compile(r"\\bsynth\\b")  # hoisted once\n\ndef process(rows):\n    for row in rows:                 # generator, not a list\n        data = orjson.loads(row)\n        if PATTERN.search(data["text"]):\n            yield transform(data)',
      },
    },
  ],

  metrics: [
    {
      icon: "account_tree",
      label: "Active workflows",
      value: "128",
      sub: "12 added this week",
      trend: { dir: "up", value: "+12%" },
      color: "primary",
    },
    {
      icon: "bolt",
      label: "Executions today",
      value: "12,847",
      sub: "across 7 providers",
      trend: { dir: "up", value: "+5.2%" },
      color: "teal",
    },
    {
      icon: "check_circle",
      label: "Success rate",
      value: "98.4%",
      sub: "30-day rolling",
      trend: { dir: "flat", value: "Steady" },
      color: "success",
    },
    {
      icon: "timer",
      label: "Avg duration",
      value: "9.2s",
      sub: "p50 across runs",
      trend: { dir: "down", value: "-0.8s" },
      color: "violet",
    },
  ],

  workflows: [
    {
      id: "wf-1",
      name: "Daily digest",
      desc: "RSS + GitHub + Gmail → summary",
      last: "Today · 09:00",
      status: "active",
      total: 1247,
      spark: [4, 6, 5, 8, 7, 9, 8, 10, 9, 11],
      owner: "AK",
    },
    {
      id: "wf-2",
      name: "Summarise inbox",
      desc: "Triage + label unread mail",
      last: "Today · 08:14",
      status: "active",
      total: 582,
      spark: [3, 4, 4, 5, 6, 5, 7, 6, 8, 7],
      owner: "AK",
    },
    {
      id: "wf-3",
      name: "Voice notes → tasks",
      desc: "Kokoro transcribe → Linear issues",
      last: "Yesterday",
      status: "active",
      total: 311,
      spark: [2, 3, 3, 4, 3, 5, 4, 6, 5, 6],
      owner: "MJ",
    },
    {
      id: "wf-4",
      name: "Code review bot",
      desc: "Diff → review comments on PRs",
      last: "Mar 18",
      status: "paused",
      total: 97,
      spark: [5, 4, 3, 3, 2, 2, 1, 1, 2, 1],
      owner: "AK",
    },
    {
      id: "wf-5",
      name: "GitHub digest",
      desc: "Star + release watch → Slack",
      last: "Mar 12",
      status: "active",
      total: 44,
      spark: [1, 2, 2, 3, 2, 3, 4, 3, 5, 4],
      owner: "TS",
    },
  ],

  executions: [
    {
      id: "ex-9210",
      wf: "Daily digest",
      status: "success",
      dur: "12.4s",
      at: "12:41:08",
    },
    {
      id: "ex-9209",
      wf: "Summarise inbox",
      status: "success",
      dur: "8.1s",
      at: "12:38:52",
    },
    {
      id: "ex-9208",
      wf: "Voice notes → tasks",
      status: "running",
      dur: "—",
      at: "12:37:14",
    },
    {
      id: "ex-9207",
      wf: "GitHub digest",
      status: "failed",
      dur: "4.7s",
      at: "12:31:09",
    },
    {
      id: "ex-9206",
      wf: "Daily digest",
      status: "success",
      dur: "11.9s",
      at: "12:18:32",
    },
    {
      id: "ex-9205",
      wf: "Code review bot",
      status: "success",
      dur: "6.3s",
      at: "12:02:50",
    },
  ],

  schedules: [
    {
      id: "s1",
      wf: "Daily digest",
      cron: "0 9 * * *",
      human: "Every day at 09:00",
      next: "Tomorrow · 09:00",
      tz: "UTC",
      status: "active",
    },
    {
      id: "s2",
      wf: "Summarise inbox",
      cron: "*/30 * * * *",
      human: "Every 30 minutes",
      next: "In 18 min",
      tz: "UTC",
      status: "active",
    },
    {
      id: "s3",
      wf: "GitHub digest",
      cron: "0 18 * * 5",
      human: "Fridays at 18:00",
      next: "Fri · 18:00",
      tz: "UTC",
      status: "active",
    },
    {
      id: "s4",
      wf: "Code review bot",
      cron: "0 * * * *",
      human: "Hourly",
      next: "Paused",
      tz: "UTC",
      status: "paused",
    },
    {
      id: "s5",
      wf: "Voice notes → tasks",
      cron: "15 7 * * 1-5",
      human: "Weekdays at 07:15",
      next: "Mon · 07:15",
      tz: "CET",
      status: "active",
    },
  ],

  voices: [
    {
      id: "af_heart",
      name: "Heart",
      lang: "en-US",
      gender: "F",
      primary: true,
    },
    { id: "af_sky", name: "Sky", lang: "en-US", gender: "F" },
    { id: "am_michael", name: "Michael", lang: "en-US", gender: "M" },
    { id: "am_adam", name: "Adam", lang: "en-US", gender: "M" },
    { id: "bf_emma", name: "Emma", lang: "en-GB", gender: "F" },
    { id: "bm_george", name: "George", lang: "en-GB", gender: "M" },
    { id: "jf_alpha", name: "Alpha", lang: "ja-JP", gender: "F" },
    { id: "zm_yun", name: "Yun", lang: "zh-CN", gender: "M" },
    { id: "ef_lucia", name: "Lucia", lang: "es-ES", gender: "F" },
  ],

  providers: [
    {
      id: "google",
      name: "Google AI",
      models: "Gemini 1.5 / 2.0",
      status: "connected",
      color: "teal",
    },
    {
      id: "openai",
      name: "OpenAI",
      models: "GPT-4o / o1",
      status: "connected",
      color: "primary",
    },
    {
      id: "anthropic",
      name: "Anthropic",
      models: "Claude 3.7",
      status: "connected",
      color: "violet",
    },
    {
      id: "local",
      name: "Local (Ollama)",
      models: "Llama 3.1 70B",
      status: "offline",
      color: "muted",
    },
  ],

  apiKeys: [
    {
      id: "k1",
      label: "Production",
      prefix: "knik_live_8f3a",
      created: "Mar 02, 2026",
      lastUsed: "2 min ago",
      scope: "full",
    },
    {
      id: "k2",
      label: "CI / Deploy",
      prefix: "knik_ci_2b91",
      created: "Feb 18, 2026",
      lastUsed: "1 hr ago",
      scope: "write",
    },
    {
      id: "k3",
      label: "Read-only",
      prefix: "knik_ro_77de",
      created: "Jan 30, 2026",
      lastUsed: "3 days ago",
      scope: "read",
    },
  ],

  mcpTools: [
    { name: "shell", cat: "System", count: 4 },
    { name: "filesystem", cat: "System", count: 6 },
    { name: "github", cat: "Dev", count: 5 },
    { name: "browser", cat: "Web", count: 3 },
    { name: "gmail", cat: "Comms", count: 4 },
    { name: "slack", cat: "Comms", count: 3 },
    { name: "calendar", cat: "Comms", count: 3 },
  ],
};

Object.assign(window, { KNIK });
