from .utils_defs import UTILS_DEFINITIONS
from .text_defs import TEXT_DEFINITIONS
from .shell_defs import SHELL_DEFINITIONS
from .file_defs import FILE_DEFINITIONS

ALL_DEFINITIONS = UTILS_DEFINITIONS + TEXT_DEFINITIONS + SHELL_DEFINITIONS + FILE_DEFINITIONS

__all__ = ['ALL_DEFINITIONS', 'UTILS_DEFINITIONS', 'TEXT_DEFINITIONS', 'SHELL_DEFINITIONS', 'FILE_DEFINITIONS']
