from .browser_defs import BROWSER_DEFINITIONS
from .cron_defs import CRON_DEFINITIONS
from .file_defs import FILE_DEFINITIONS
from .shell_defs import SHELL_DEFINITIONS
from .text_defs import TEXT_DEFINITIONS
from .utils_defs import UTILS_DEFINITIONS
from .workflow_defs import WORKFLOW_DEFINITIONS


ALL_DEFINITIONS = (
    UTILS_DEFINITIONS
    + TEXT_DEFINITIONS
    + SHELL_DEFINITIONS
    + FILE_DEFINITIONS
    + CRON_DEFINITIONS
    + BROWSER_DEFINITIONS
    + WORKFLOW_DEFINITIONS
)

__all__ = [
    "ALL_DEFINITIONS",
    "UTILS_DEFINITIONS",
    "TEXT_DEFINITIONS",
    "SHELL_DEFINITIONS",
    "FILE_DEFINITIONS",
    "CRON_DEFINITIONS",
    "BROWSER_DEFINITIONS",
    "WORKFLOW_DEFINITIONS",
]
