from .utils_impl import UTILS_IMPLEMENTATIONS
from .text_impl import TEXT_IMPLEMENTATIONS
from .shell_impl import SHELL_IMPLEMENTATIONS

ALL_IMPLEMENTATIONS = {**UTILS_IMPLEMENTATIONS, **TEXT_IMPLEMENTATIONS, **SHELL_IMPLEMENTATIONS}

__all__ = ['ALL_IMPLEMENTATIONS', 'UTILS_IMPLEMENTATIONS', 'TEXT_IMPLEMENTATIONS', 'SHELL_IMPLEMENTATIONS']
