from .utils_defs import UTILS_DEFINITIONS
from .text_defs import TEXT_DEFINITIONS

ALL_DEFINITIONS = UTILS_DEFINITIONS + TEXT_DEFINITIONS

__all__ = ['ALL_DEFINITIONS', 'UTILS_DEFINITIONS', 'TEXT_DEFINITIONS']
